"""
Creates the folder structure where the files generated by padding strategies are stored. 
"""
import os

root_folder = "../Data"


def create_groundtruth_folder():
    os.makedirs(os.path.join(root_folder, "Processed", "groundTruthFeatures"))


def create_existing_padding_folder():
    for folder in ["Exponential", "Linear", "Mouse_elephant", "MTU", "Random", "Random255"]:
        os.makedirs(os.path.join(root_folder, "Processed", "padding_data", "Existing", folder))
        os.makedirs(os.path.join(root_folder, "Processed", "padding_features", folder))


def create_proposal_padding_folder():
    for folder in ["100", "500", "700", "900"]:
        os.makedirs(os.path.join(root_folder, "Processed", "padding_data", "Proposal", folder))
        os.makedirs(os.path.join(root_folder, "Processed", "padding_features", folder))


if __name__ == "__main__":
    create_groundtruth_folder()
    create_existing_padding_folder()
    create_proposal_padding_folder()
